var productData = [
 {
   "productNo": 1,
   "productName": "Design1",
   "price": 10,
   "mainImage": "product1.jpg",
   "thumb1": "",
   "thumb2": "",
   "thumb3": "",
   "thumb4": "",
   "productP1": "This is the first product",
   "productP2": "This product is very cool",
   "productP3": "",
   "productP4": "",
   "productP5": ""
 },
 {
   "productNo": 2,
   "productName": "Design2",
   "price": 10,
   "mainImage": "product2.jpg",
   "thumb1": "",
   "thumb2": "",
   "thumb3": "",
   "thumb4": "",
   "productP1": "This is the second product",
   "productP2": "This product is very cool",
   "productP3": "",
   "productP4": "",
   "productP5": ""
 },
 {
   "productNo": 3,
   "productName": "Design3",
   "price": 10,
   "mainImage": "product3.jpg",
   "thumb1": "",
   "thumb2": "",
   "thumb3": "",
   "thumb4": "",
   "productP1": "This is the third product",
   "productP2": "This product is very cool",
   "productP3": "",
   "productP4": "",
   "productP5": ""
 },
 {
   "productNo": 4,
   "productName": "Design4",
   "price": 10,
   "mainImage": "product4.jpg",
   "thumb1": "",
   "thumb2": "",
   "thumb3": "",
   "thumb4": "",
   "productP1": "This is the fourth product",
   "productP2": "This product is very cool",
   "productP3": "",
   "productP4": "",
   "productP5": ""
 },
 {
   "productNo": 5,
   "productName": "Design5",
   "price": 10,
   "mainImage": "product5.jpg",
   "thumb1": "",
   "thumb2": "",
   "thumb3": "",
   "thumb4": "",
   "productP1": "This is the fifth product",
   "productP2": "This product is very cool",
   "productP3": "",
   "productP4": "",
   "productP5": ""
 }
]